# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.event_pb2 as event__pb2


class EventStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPartecipants = channel.unary_unary(
            "/event.Event/GetPartecipants",
            request_serializer=event__pb2.EventID.SerializeToString,
            response_deserializer=event__pb2.Partecipants.FromString,
        )


class EventServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPartecipants(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EventServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetPartecipants": grpc.unary_unary_rpc_method_handler(
            servicer.GetPartecipants,
            request_deserializer=event__pb2.EventID.FromString,
            response_serializer=event__pb2.Partecipants.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "event.Event", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Event(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPartecipants(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/event.Event/GetPartecipants",
            event__pb2.EventID.SerializeToString,
            event__pb2.Partecipants.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
