# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\x12\x05\x65vent\"\x15\n\x07\x45ventID\x12\n\n\x02id\x18\x01 \x01(\t\"$\n\x0cPartecipants\x12\x14\n\x0cpartecipants\x18\x01 \x03(\t2?\n\x05\x45vent\x12\x36\n\x0fGetPartecipants\x12\x0e.event.EventID\x1a\x13.event.Partecipantsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EVENTID']._serialized_start=22
  _globals['_EVENTID']._serialized_end=43
  _globals['_PARTECIPANTS']._serialized_start=45
  _globals['_PARTECIPANTS']._serialized_end=81
  _globals['_EVENT']._serialized_start=83
  _globals['_EVENT']._serialized_end=146
# @@protoc_insertion_point(module_scope)
