# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.match_pb2 as match__pb2


class MatchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MatchStart = channel.unary_unary(
            "/match.Match/MatchStart",
            request_serializer=match__pb2.EventID.SerializeToString,
            response_deserializer=match__pb2.Response.FromString,
        )
        self.MatchStop = channel.unary_unary(
            "/match.Match/MatchStop",
            request_serializer=match__pb2.EventID.SerializeToString,
            response_deserializer=match__pb2.Response.FromString,
        )
        self.MatchAnswer = channel.unary_unary(
            "/match.Match/MatchAnswer",
            request_serializer=match__pb2.AnswerRequest.SerializeToString,
            response_deserializer=match__pb2.Response.FromString,
        )


class MatchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MatchStart(self, request, context):
        """Start the match of an event"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def MatchStop(self, request, context):
        """Stop the match of an event"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def MatchAnswer(self, request, context):
        """Get the answer of the user"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MatchServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "MatchStart": grpc.unary_unary_rpc_method_handler(
            servicer.MatchStart,
            request_deserializer=match__pb2.EventID.FromString,
            response_serializer=match__pb2.Response.SerializeToString,
        ),
        "MatchStop": grpc.unary_unary_rpc_method_handler(
            servicer.MatchStop,
            request_deserializer=match__pb2.EventID.FromString,
            response_serializer=match__pb2.Response.SerializeToString,
        ),
        "MatchAnswer": grpc.unary_unary_rpc_method_handler(
            servicer.MatchAnswer,
            request_deserializer=match__pb2.AnswerRequest.FromString,
            response_serializer=match__pb2.Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "match.Match", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Match(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MatchStart(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/match.Match/MatchStart",
            match__pb2.EventID.SerializeToString,
            match__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def MatchStop(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/match.Match/MatchStop",
            match__pb2.EventID.SerializeToString,
            match__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def MatchAnswer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/match.Match/MatchAnswer",
            match__pb2.AnswerRequest.SerializeToString,
            match__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
