# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmatch.proto\x12\x05match\"\x14\n\x06UserID\x12\n\n\x02ID\x18\x01 \x01(\t\"\x15\n\x07\x45ventID\x12\n\n\x02ID\x18\x01 \x01(\t\"J\n\rAnswerRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\r\n\x05\x65vent\x18\x02 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x03 \x01(\x05\x12\x0c\n\x04\x65val\x18\x04 \x01(\x05\"-\n\x08Response\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2\x9a\x01\n\x05Match\x12-\n\nMatchStart\x12\x0e.match.EventID\x1a\x0f.match.Response\x12,\n\tMatchStop\x12\x0e.match.EventID\x1a\x0f.match.Response\x12\x34\n\x0bMatchAnswer\x12\x14.match.AnswerRequest\x1a\x0f.match.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'match_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USERID']._serialized_start=22
  _globals['_USERID']._serialized_end=42
  _globals['_EVENTID']._serialized_start=44
  _globals['_EVENTID']._serialized_end=65
  _globals['_ANSWERREQUEST']._serialized_start=67
  _globals['_ANSWERREQUEST']._serialized_end=141
  _globals['_RESPONSE']._serialized_start=143
  _globals['_RESPONSE']._serialized_end=188
  _globals['_MATCH']._serialized_start=191
  _globals['_MATCH']._serialized_end=345
# @@protoc_insertion_point(module_scope)
