# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"I\n\x0bSendRequest\x12\x0e\n\x06UserId\x18\x01 \x01(\t\x12\x0b\n\x03\x41PI\x18\x02 \x01(\t\x12\x0c\n\x04What\x18\x03 \x01(\t\x12\x0f\n\x07\x43ontent\x18\x04 \x01(\t\"\'\n\x08Response\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t25\n\x08UserSend\x12)\n\x04Send\x12\x11.user.SendRequest\x1a\x0e.user.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SENDREQUEST']._serialized_start=20
  _globals['_SENDREQUEST']._serialized_end=93
  _globals['_RESPONSE']._serialized_start=95
  _globals['_RESPONSE']._serialized_end=134
  _globals['_USERSEND']._serialized_start=136
  _globals['_USERSEND']._serialized_end=189
# @@protoc_insertion_point(module_scope)
